services:
  app:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true
    environment:
      - PORT=4000
    ports:
      - 4000:4000
